Assignment1 (#8)
* Initial commit.

* Fixed position of the Library Flags.
Led to the error "undefined reference to xercerc" on some machines.

* resolve compile error for gcc > 4.5

* simple cmake support

* more sensible name padding

* updated libxsd

* added todos

* updated vtk stuff

* updated vtk stuff

* WIP improving cmake

* fixed file suffix

* formatting + warnings for icpc

* removed old makefiles

* Setting default build type

* empty doxygen module

* class doc

* include headers :/

* now propperly generated

* ignore more warnings

* include guards -> pragma once

* formatting

* Increased min CMake Version

* lang def can cause errors

* moved libxsd

* removed unnecessary ;

* raise c++ standard to 14

* added rudimentary gitignore

* added new version of Maxwell Boltzmann Distribution

* add free functions and operators for array math

* Documentation and stream operator for containers

* some refactoring for sanity:
- iterator while loops to range based for
- simplified if
- constexpr
- cleaned up inputs
- doc

* removed Vector class and replaced everything through std::array

* declare trivial constructors / destructors default

* remove extra calcF

* removed all using namespace std

* Add missing return doc

* Add missing include

* fix typo

* add todo for hint

* make getter and toString const

* added dimension option to maxwell boltzmann

* only instantiate container operators for containers

* Move input to new input folder

* fixed copy&paste doc error

* Update C++ standard to 17

* Rework .gitignore

- Include anything from the github C++ template
- Add vscode/ project folder
- guess that most vscode students will name their build folder "build"

* Aggressivly ignore build folders

* test only, do not merge yet
for the rest follow the order in the worksheet, in the assignement branch

* init Assignment1

* fix

* cleanup

* gitignore

* Change outputs for prettier printing (#2)

* Added CMAKE_BUILD_TYPE "Debug" for full console output, use default for clean output

* added DEBUG_PRINT to all irrelevant prints, cleaned up progress print of simulation

* changed IO to optarg, still unsre about output directory

---------

Co-authored-by: jkr11 <113939131+jkr11@users.noreply.github.com>

* add documentation

* cleanup includes, add pragmas

* fix optarg merge, string cant be constexpr, change file reader to use std::string

* Started documenting, moved some implementation stuff from 'ParticleContainer.h' to 'ParticleContainer.cpp' and fixed minor issue with constexpr string in
'MolSim.cpp'

* More documentation

* TaskDummyPR (#1)

* first pull request

* first task correct

* does workflow trigger

* - exclude custom shell scripts in gitignore
- added clang format configuration

* more debug print cleanup and new Usage print on erroneous execution

* more Info on error for -t and -d

* new clang format for github actions test without any changes to files

---------

Co-authored-by: breuera <breuera@TUM-I5>
Co-authored-by: Wolfgang Eckhardt <eckhardw@in.tum.de>
Co-authored-by: FG-TUM <f.gratl@tum.de>
Co-authored-by: FG-TUM <FG-TUM@users.noreply.github.com>
Co-authored-by: Samuel Newcome <samuel.newcome@tum.de>
Co-authored-by: Maximilian Böhmichen <34962223+MaximilianBoehmichen@users.noreply.github.com>
Co-authored-by: Michael Carnuth <m.carnuth@tum.de>
Co-authored-by: Maximilian Böhmichen <max@boehmichen.de>